import Foundation

extension EntryLinkRegistry {
    static func criticalCareDepthLinks() -> [EntryLink] {
        [
            EntryLink(from: "reference:oxygen-device-bedside-checks", to: "procedure:oxygen-administration", relation: .seeAlso),
            EntryLink(from: "reference:oxygen-device-bedside-checks", to: "procedure:pulse-oximetry", relation: .seeAlso),
            EntryLink(from: "reference:oxygen-device-bedside-checks", to: "reference:focused-respiratory-assessment", relation: .seeAlso),
            EntryLink(from: "reference:oxygenation-versus-ventilation", to: "lab:abg", relation: .seeAlso),
            EntryLink(from: "reference:oxygenation-versus-ventilation", to: "lab:capnography-etco2", relation: .seeAlso),
            EntryLink(from: "reference:oxygenation-versus-ventilation", to: "reference:abg-algorithm", relation: .seeAlso),
            EntryLink(from: "reference:high-flow-nasal-cannula-monitoring", to: "reference:oxygen-device-bedside-checks", relation: .seeAlso),
            EntryLink(from: "reference:high-flow-nasal-cannula-monitoring", to: "diagnosis:ards", relation: .seeAlso),
            EntryLink(from: "reference:high-flow-nasal-cannula-monitoring", to: "reference:oxygenation-versus-ventilation", relation: .seeAlso),
            EntryLink(from: "reference:noninvasive-ventilation-bedside-assessment", to: "reference:cpap-daily-support", relation: .seeAlso),
            EntryLink(from: "reference:noninvasive-ventilation-bedside-assessment", to: "reference:oxygenation-versus-ventilation", relation: .seeAlso),
            EntryLink(from: "reference:noninvasive-ventilation-bedside-assessment", to: "reference:high-flow-nasal-cannula-monitoring", relation: .seeAlso),
            EntryLink(from: "reference:ventilator-bedside-assessment", to: "reference:mechanical-ventilation-basics", relation: .seeAlso),
            EntryLink(from: "reference:ventilator-bedside-assessment", to: "reference:mechanical-ventilation-modes-selection", relation: .seeAlso),
            EntryLink(from: "reference:ventilator-bedside-assessment", to: "reference:patient-ventilator-asynchrony-recognition", relation: .seeAlso),
            EntryLink(from: "reference:ventilator-waveform-observation", to: "reference:patient-ventilator-asynchrony-recognition", relation: .seeAlso),
            EntryLink(from: "reference:ventilator-waveform-observation", to: "reference:auto-peep-and-ineffective-triggering", relation: .seeAlso),
            EntryLink(from: "reference:ventilator-waveform-observation", to: "reference:mechanical-ventilation-modes-selection", relation: .seeAlso),
            EntryLink(from: "reference:patient-ventilator-asynchrony-recognition", to: "reference:rass-scale", relation: .seeAlso),
            EntryLink(from: "reference:auto-peep-and-ineffective-triggering", to: "diagnosis:copd", relation: .seeAlso),
            EntryLink(from: "reference:auto-peep-and-ineffective-triggering", to: "reference:patient-ventilator-asynchrony-recognition", relation: .seeAlso),
            EntryLink(from: "reference:artificial-airway-secretion-assessment", to: "procedure:tracheal-suctioning", relation: .seeAlso),
            EntryLink(from: "reference:artificial-airway-secretion-assessment", to: "procedure:oral-suctioning", relation: .seeAlso),
            EntryLink(from: "reference:artificial-airway-secretion-assessment", to: "reference:tracheostomy-bedside-safety-checks", relation: .seeAlso),
            EntryLink(from: "reference:tracheostomy-bedside-safety-checks", to: "procedure:tracheostomy-care", relation: .seeAlso),
            EntryLink(from: "reference:tracheostomy-bedside-safety-checks", to: "scenario:trach-emergency-scenario", relation: .seeAlso),
            EntryLink(from: "reference:tracheostomy-bedside-safety-checks", to: "reference:communication-when-speech-is-limited", relation: .seeAlso),
            EntryLink(from: "reference:ventilator-liberation-observation", to: "procedure:spontaneous-breathing-trial", relation: .seeAlso),
            EntryLink(from: "reference:ventilator-liberation-observation", to: "reference:artificial-airway-secretion-assessment", relation: .seeAlso),
            EntryLink(from: "reference:ventilator-liberation-observation", to: "reference:post-extubation-observation", relation: .seeAlso),
            EntryLink(from: "reference:post-extubation-observation", to: "reference:oxygen-device-bedside-checks", relation: .seeAlso),
            EntryLink(from: "reference:post-extubation-observation", to: "reference:focused-respiratory-assessment", relation: .seeAlso),
            EntryLink(from: "reference:telemetry-signal-quality", to: "procedure:twelve-lead-ecg", relation: .seeAlso),
            EntryLink(from: "reference:telemetry-signal-quality", to: "reference:ecg-rate-and-interval-review", relation: .seeAlso),
            EntryLink(from: "reference:telemetry-signal-quality", to: "reference:rhythm-change-bedside-assessment", relation: .seeAlso),
            EntryLink(from: "reference:ecg-rate-and-interval-review", to: "reference:ecg-12-lead-basics", relation: .seeAlso),
            EntryLink(from: "reference:ecg-rate-and-interval-review", to: "reference:av-blocks-reference", relation: .seeAlso),
            EntryLink(from: "reference:ecg-rate-and-interval-review", to: "reference:qt-interval-monitoring-context", relation: .seeAlso),
            EntryLink(from: "reference:rhythm-change-bedside-assessment", to: "reference:ecg-rate-and-interval-review", relation: .seeAlso),
            EntryLink(from: "reference:rhythm-change-bedside-assessment", to: "diagnosis:atrial-fibrillation", relation: .seeAlso),
            EntryLink(from: "reference:qt-interval-monitoring-context", to: "lab:potassium", relation: .seeAlso),
            EntryLink(from: "reference:qt-interval-monitoring-context", to: "lab:magnesium", relation: .seeAlso),
            EntryLink(from: "reference:adult-cpr-quality-review", to: "procedure:adult-bls", relation: .seeAlso),
            EntryLink(from: "reference:adult-cpr-quality-review", to: "reference:code-blue-roles", relation: .seeAlso),
            EntryLink(from: "reference:adult-cpr-quality-review", to: "reference:resuscitation-airway-capnography", relation: .seeAlso),
            EntryLink(from: "reference:resuscitation-airway-capnography", to: "lab:capnography-etco2", relation: .seeAlso),
            EntryLink(from: "reference:resuscitation-airway-capnography", to: "procedure:intubation-assist", relation: .seeAlso),
            EntryLink(from: "reference:post-arrest-assessment-priorities", to: "reference:resuscitation-airway-capnography", relation: .seeAlso),
            EntryLink(from: "reference:post-arrest-assessment-priorities", to: "reference:cardiac-arrest-recovery-support", relation: .seeAlso),
            EntryLink(from: "reference:post-arrest-assessment-priorities", to: "reference:post-icu-recovery", relation: .seeAlso),
            EntryLink(from: "reference:cardiac-arrest-recovery-support", to: "reference:post-icu-recovery", relation: .seeAlso),
            EntryLink(from: "reference:cardiac-arrest-recovery-support", to: "reference:code-blue-roles", relation: .seeAlso)
        ]
    }
}
