import Foundation

extension EntryLinkRegistry {
    /// Fifth batch: first curated slice of the propose-links.py review queue
    /// (4+ mention candidates, hand-reviewed). Relations corrected where the
    /// generator's suggestion was wrong — a drug that CAUSES a condition gets
    /// seeAlso, never usedFor. Noise dropped: communication entries matching
    /// vignette text, duplicate-entry targets, pairs already in FamilyLinks.
    static func curatedLinks01() -> [EntryLink] {
        [
            // ===== Anticoagulation / hematology =====
            EntryLink(from: "drug:heparin", to: "diagnosis:hit", relation: .seeAlso),
            EntryLink(from: "drug:argatroban", to: "diagnosis:hit", relation: .usedFor),
            EntryLink(from: "drug:argatroban", to: "drug:heparin", relation: .seeAlso),
            EntryLink(from: "drug:bivalirudin", to: "drug:heparin", relation: .seeAlso),
            EntryLink(from: "lab:activated-clotting-time", to: "drug:heparin", relation: .seeAlso),
            EntryLink(from: "lab:activated-clotting-time", to: "drug:bivalirudin", relation: .seeAlso),
            EntryLink(from: "reference:anticoagulation-reversal-reference", to: "drug:idarucizumab", relation: .seeAlso),
            EntryLink(from: "reference:anticoagulation-reversal-reference", to: "drug:vitamin-k", relation: .seeAlso),
            EntryLink(from: "reference:anticoagulation-reversal-reference", to: "drug:warfarin", relation: .seeAlso),
            EntryLink(from: "reference:anticoagulation-reversal-reference", to: "drug:dabigatran", relation: .seeAlso),
            EntryLink(from: "reference:anticoagulation-reversal-strategies", to: "drug:heparin", relation: .seeAlso),
            EntryLink(from: "reference:anticoagulation-reversal-strategies", to: "drug:ticagrelor", relation: .seeAlso),
            EntryLink(from: "reference:coagulation-panel-interpretation", to: "drug:warfarin", relation: .seeAlso),
            EntryLink(from: "reference:coagulation-panel-interpretation", to: "drug:heparin", relation: .seeAlso),
            EntryLink(from: "reference:coagulation-panel-interpretation", to: "lab:fibrinogen", relation: .seeAlso),
            EntryLink(from: "reference:coagulation-panel-interpretation", to: "lab:d-dimer", relation: .seeAlso),
            EntryLink(from: "diagnosis:antiphospholipid-syndrome", to: "drug:warfarin", relation: .seeAlso),
            EntryLink(from: "diagnosis:antiphospholipid-syndrome", to: "drug:aspirin", relation: .seeAlso),

            // ===== Cardiovascular =====
            EntryLink(from: "drug:aspirin-low-dose", to: "diagnosis:preeclampsia", relation: .usedFor),
            EntryLink(from: "drug:aspirin-low-dose", to: "diagnosis:stroke", relation: .usedFor),
            EntryLink(from: "drug:aspirin-low-dose", to: "drug:aspirin", relation: .seeAlso),
            EntryLink(from: "drug:clevidipine", to: "diagnosis:aortic-dissection", relation: .usedFor),
            EntryLink(from: "drug:clevidipine", to: "drug:esmolol", relation: .seeAlso),
            EntryLink(from: "drug:milrinone", to: "diagnosis:cardiogenic-shock", relation: .usedFor),
            EntryLink(from: "drug:isoproterenol", to: "drug:atropine", relation: .seeAlso),
            EntryLink(from: "drug:lidocaine-iv-antiarrhythmic", to: "drug:lidocaine", relation: .seeAlso),
            EntryLink(from: "drug:lidocaine-iv-antiarrhythmic", to: "drug:amiodarone", relation: .seeAlso),
            EntryLink(from: "diagnosis:hypertensive-emergency", to: "diagnosis:eclampsia", relation: .seeAlso),
            EntryLink(from: "diagnosis:hypertensive-emergency", to: "diagnosis:stroke", relation: .seeAlso),
            EntryLink(from: "reference:hypertensive-emergency-management", to: "diagnosis:aortic-dissection", relation: .seeAlso),
            EntryLink(from: "reference:hypertensive-emergency-management", to: "diagnosis:eclampsia", relation: .seeAlso),
            EntryLink(from: "reference:hypertensive-emergency-management", to: "drug:clevidipine", relation: .seeAlso),
            EntryLink(from: "reference:hypertensive-emergency-management", to: "drug:labetalol", relation: .seeAlso),
            EntryLink(from: "reference:shock-hemodynamic-patterns", to: "drug:norepinephrine", relation: .seeAlso),
            EntryLink(from: "reference:shock-hemodynamic-patterns", to: "diagnosis:pneumothorax", relation: .seeAlso),
            EntryLink(from: "diagnosis:acute-decompensated-heart-failure", to: "diagnosis:atrial-fibrillation", relation: .seeAlso),
            EntryLink(from: "diagnosis:acute-limb-ischemia", to: "diagnosis:atrial-fibrillation", relation: .seeAlso),
            EntryLink(from: "diagnosis:acute-limb-ischemia", to: "scenario:compartment-syndrome-scenario", relation: .seeAlso),
            EntryLink(from: "diagnosis:submassive-massive-pulmonary-embolism", to: "diagnosis:cteph", relation: .seeAlso),
            EntryLink(from: "diagnosis:submassive-massive-pulmonary-embolism", to: "diagnosis:pulmonary-hypertension", relation: .seeAlso),
            EntryLink(from: "diagnosis:submassive-massive-pulmonary-embolism", to: "drug:alteplase", relation: .seeAlso),

            // ===== Toxicology =====
            EntryLink(from: "diagnosis:beta-blocker-toxicity", to: "drug:propranolol", relation: .seeAlso),
            EntryLink(from: "diagnosis:beta-blocker-toxicity", to: "drug:sotalol", relation: .seeAlso),
            EntryLink(from: "diagnosis:ccb-toxicity", to: "drug:verapamil", relation: .seeAlso),
            EntryLink(from: "diagnosis:ccb-toxicity", to: "drug:diltiazem-po", relation: .seeAlso),
            EntryLink(from: "diagnosis:anticholinergic-poisoning", to: "drug:diphenhydramine", relation: .seeAlso),
            EntryLink(from: "diagnosis:acetaminophen-overdose", to: "drug:acetaminophen", relation: .seeAlso),
            EntryLink(from: "diagnosis:acetaminophen-overdose", to: "drug:n-acetylcysteine", relation: .seeAlso),
            EntryLink(from: "diagnosis:acetaminophen-overdose", to: "diagnosis:acute-liver-failure", relation: .seeAlso),
            EntryLink(from: "diagnosis:acute-liver-failure", to: "drug:acetaminophen", relation: .seeAlso),
            EntryLink(from: "diagnosis:acute-liver-failure", to: "diagnosis:hypoglycemia", relation: .seeAlso),
            EntryLink(from: "drug:digoxin-immune-fab", to: "lab:digoxin-level", relation: .seeAlso),
            EntryLink(from: "drug:pentamidine", to: "diagnosis:hypoglycemia", relation: .seeAlso),

            // ===== Electrolytes / renal =====
            EntryLink(from: "drug:calcium-chloride", to: "diagnosis:hyperkalemia", relation: .usedFor),
            EntryLink(from: "drug:calcium-chloride", to: "diagnosis:hypocalcemia", relation: .usedFor),
            EntryLink(from: "drug:sodium-bicarbonate", to: "lab:bicarbonate", relation: .monitorsWith),
            EntryLink(from: "drug:sodium-bicarbonate", to: "diagnosis:hyperkalemia", relation: .usedFor),
            EntryLink(from: "diagnosis:severe-hyperkalemia", to: "diagnosis:hyperkalemia", relation: .seeAlso),
            EntryLink(from: "diagnosis:rhabdomyolysis", to: "diagnosis:hyperkalemia", relation: .seeAlso),
            EntryLink(from: "diagnosis:aki", to: "diagnosis:hyperkalemia", relation: .seeAlso),
            EntryLink(from: "lab:potassium", to: "diagnosis:hypokalemia", relation: .seeAlso),
            EntryLink(from: "lab:ionized-calcium", to: "diagnosis:hypocalcemia", relation: .seeAlso),
            EntryLink(from: "lab:ionized-calcium", to: "lab:vitamin-d-25oh", relation: .interpretWith),
            EntryLink(from: "lab:arterial-blood-gas", to: "lab:anion-gap", relation: .interpretWith),
            EntryLink(from: "reference:abg-vbg-interpretation", to: "lab:anion-gap", relation: .seeAlso),
            EntryLink(from: "reference:abg-vbg-interpretation", to: "lab:lactate", relation: .seeAlso),
            EntryLink(from: "diagnosis:adult-dka", to: "lab:anion-gap", relation: .assessedBy),
            EntryLink(from: "diagnosis:adult-dka", to: "lab:bicarbonate", relation: .assessedBy),
            EntryLink(from: "diagnosis:adult-dka", to: "diagnosis:dka", relation: .seeAlso),

            // ===== Endocrine =====
            EntryLink(from: "diagnosis:addisons", to: "drug:hydrocortisone", relation: .seeAlso),
            EntryLink(from: "diagnosis:addisons", to: "lab:cortisol", relation: .assessedBy),
            EntryLink(from: "diagnosis:adrenal-crisis", to: "drug:hydrocortisone", relation: .seeAlso),
            EntryLink(from: "diagnosis:adrenal-crisis", to: "lab:cortisol", relation: .assessedBy),
            EntryLink(from: "diagnosis:adrenal-crisis", to: "diagnosis:hypoglycemia", relation: .seeAlso),
            EntryLink(from: "diagnosis:hypopituitarism", to: "diagnosis:adrenal-crisis", relation: .seeAlso),
            EntryLink(from: "diagnosis:hypopituitarism", to: "diagnosis:hypothyroidism", relation: .seeAlso),
            EntryLink(from: "diagnosis:hypopituitarism", to: "drug:hydrocortisone", relation: .seeAlso),
            EntryLink(from: "diagnosis:hypopituitarism", to: "lab:cortisol", relation: .assessedBy),
            EntryLink(from: "diagnosis:hypopituitarism", to: "lab:free-t4", relation: .assessedBy),
            EntryLink(from: "lab:acth-stimulation-test", to: "lab:cortisol", relation: .interpretWith),
            EntryLink(from: "lab:acth-stimulation-test", to: "drug:hydrocortisone", relation: .seeAlso),
            EntryLink(from: "reference:cushing-workup", to: "lab:cortisol", relation: .seeAlso),
            EntryLink(from: "reference:cushing-workup", to: "diagnosis:cushing-syndrome", relation: .seeAlso),
            EntryLink(from: "diagnosis:acromegaly", to: "diagnosis:hypopituitarism", relation: .seeAlso),
            EntryLink(from: "diagnosis:acromegaly", to: "drug:pegvisomant", relation: .seeAlso),
            EntryLink(from: "lab:igf-1", to: "diagnosis:acromegaly", relation: .seeAlso),
            EntryLink(from: "lab:igf-1", to: "drug:pegvisomant", relation: .seeAlso),
            EntryLink(from: "diagnosis:hypoparathyroidism", to: "diagnosis:hypocalcemia", relation: .seeAlso),
            EntryLink(from: "diagnosis:hypoparathyroidism", to: "lab:vitamin-d-25oh", relation: .assessedBy),
            EntryLink(from: "diagnosis:hypoparathyroidism", to: "drug:calcitriol", relation: .seeAlso),
            EntryLink(from: "diagnosis:ir-thyroiditis-immunotherapy", to: "diagnosis:hypothyroidism", relation: .seeAlso),
            EntryLink(from: "diagnosis:ir-thyroiditis-immunotherapy", to: "diagnosis:hyperthyroidism", relation: .seeAlso),
            EntryLink(from: "diagnosis:ir-thyroiditis-immunotherapy", to: "drug:levothyroxine", relation: .seeAlso),
            EntryLink(from: "diagnosis:ir-thyroiditis-immunotherapy", to: "lab:free-t4", relation: .assessedBy),
            EntryLink(from: "diagnosis:nephrogenic-diabetes-insipidus", to: "drug:lithium", relation: .seeAlso),
            EntryLink(from: "diagnosis:nephrogenic-diabetes-insipidus", to: "diagnosis:hypernatremia", relation: .seeAlso),
            EntryLink(from: "diagnosis:primary-aldosteronism", to: "diagnosis:hypokalemia", relation: .seeAlso),
            EntryLink(from: "diagnosis:primary-aldosteronism", to: "drug:spironolactone", relation: .seeAlso),
            EntryLink(from: "procedure:transsphenoidal-pituitary-surgery-care", to: "drug:hydrocortisone", relation: .seeAlso),
            EntryLink(from: "procedure:transsphenoidal-pituitary-surgery-care", to: "lab:cortisol", relation: .seeAlso),
            EntryLink(from: "reference:oral-diabetes-medications-reference", to: "drug:metformin", relation: .seeAlso),
            EntryLink(from: "reference:oral-diabetes-medications-reference", to: "diagnosis:hypoglycemia", relation: .seeAlso),
            EntryLink(from: "lab:pediatric-glucose-monitoring", to: "diagnosis:hypoglycemia", relation: .seeAlso),

            // ===== Infectious disease =====
            EntryLink(from: "reference:antibiotic-spectrum-reference", to: "drug:ceftriaxone", relation: .seeAlso),
            EntryLink(from: "reference:antibiotic-spectrum-reference", to: "drug:vancomycin", relation: .seeAlso),
            EntryLink(from: "reference:antibiotic-spectrum-reference", to: "drug:doxycycline", relation: .seeAlso),
            EntryLink(from: "reference:antibiotic-spectrum-reference", to: "drug:metronidazole", relation: .seeAlso),
            EntryLink(from: "reference:antibiotic-spectrum-reference", to: "drug:clindamycin", relation: .seeAlso),
            EntryLink(from: "reference:antifungal-classes", to: "drug:amphotericin-b", relation: .seeAlso),
            EntryLink(from: "reference:antifungal-classes", to: "drug:isavuconazole", relation: .seeAlso),
            EntryLink(from: "reference:antifungal-classes", to: "drug:voriconazole", relation: .seeAlso),
            EntryLink(from: "reference:antifungal-classes", to: "drug:fluconazole", relation: .seeAlso),
            EntryLink(from: "reference:antifungal-classes", to: "drug:itraconazole", relation: .seeAlso),
            EntryLink(from: "lab:galactomannan-bdg", to: "diagnosis:invasive-aspergillosis", relation: .seeAlso),
            EntryLink(from: "lab:galactomannan-bdg", to: "diagnosis:mucormycosis", relation: .seeAlso),
            EntryLink(from: "lab:galactomannan-bdg", to: "drug:amphotericin-b", relation: .seeAlso),
            EntryLink(from: "lab:aspergillus-precipitins", to: "diagnosis:invasive-aspergillosis", relation: .seeAlso),
            EntryLink(from: "lab:aspergillus-precipitins", to: "diagnosis:hypersensitivity-pneumonitis", relation: .seeAlso),
            EntryLink(from: "lab:aspergillus-precipitins", to: "drug:voriconazole", relation: .seeAlso),
            EntryLink(from: "diagnosis:abpa", to: "diagnosis:asthma", relation: .seeAlso),
            EntryLink(from: "diagnosis:abpa", to: "diagnosis:bronchiectasis", relation: .seeAlso),
            EntryLink(from: "diagnosis:abpa", to: "drug:itraconazole", relation: .seeAlso),
            EntryLink(from: "reference:cdc-sti-guidelines-summary", to: "diagnosis:gonorrhea", relation: .seeAlso),
            EntryLink(from: "reference:cdc-sti-guidelines-summary", to: "diagnosis:syphilis", relation: .seeAlso),
            EntryLink(from: "reference:cdc-sti-guidelines-summary", to: "drug:doxycycline", relation: .seeAlso),
            EntryLink(from: "reference:tropical-fever-workup", to: "diagnosis:malaria", relation: .seeAlso),
            EntryLink(from: "reference:tropical-fever-workup", to: "drug:doxycycline", relation: .seeAlso),
            EntryLink(from: "reference:fever-evaluation-adult", to: "diagnosis:sepsis", relation: .seeAlso),
            EntryLink(from: "reference:fever-evaluation-adult", to: "diagnosis:neutropenic-fever", relation: .seeAlso),
            EntryLink(from: "diagnosis:neonatal-sepsis-r13", to: "diagnosis:sepsis", relation: .seeAlso),
            EntryLink(from: "diagnosis:neonatal-sepsis-r13", to: "diagnosis:meningitis", relation: .seeAlso),
            EntryLink(from: "diagnosis:pediatric-fever-without-source", to: "lab:procalcitonin", relation: .assessedBy),
            EntryLink(from: "diagnosis:pediatric-fever-without-source", to: "lab:blood-culture", relation: .assessedBy),
            EntryLink(from: "diagnosis:acute-bacterial-sinusitis", to: "drug:amoxicillin-clavulanate", relation: .seeAlso),
            EntryLink(from: "diagnosis:acute-otitis-media", to: "drug:amoxicillin", relation: .seeAlso),
            EntryLink(from: "diagnosis:bowel-perforation", to: "diagnosis:diverticulitis", relation: .seeAlso),
            EntryLink(from: "diagnosis:bowel-perforation", to: "diagnosis:sepsis", relation: .seeAlso),
            EntryLink(from: "diagnosis:bowel-perforation", to: "lab:lactate", relation: .assessedBy),

            // ===== Neuro / psych =====
            EntryLink(from: "reference:seizure-aed-selection", to: "drug:levetiracetam", relation: .seeAlso),
            EntryLink(from: "reference:seizure-aed-selection", to: "drug:lamotrigine", relation: .seeAlso),
            EntryLink(from: "reference:seizure-aed-selection", to: "drug:carbamazepine", relation: .seeAlso),
            EntryLink(from: "reference:seizure-aed-selection", to: "drug:lacosamide", relation: .seeAlso),
            EntryLink(from: "reference:seizure-aed-selection", to: "drug:topiramate", relation: .seeAlso),
            EntryLink(from: "drug:lacosamide", to: "diagnosis:status-epilepticus", relation: .usedFor),
            EntryLink(from: "drug:pyridostigmine", to: "diagnosis:myasthenia-gravis", relation: .usedFor),
            EntryLink(from: "drug:pyridostigmine", to: "drug:atropine", relation: .seeAlso),
            EntryLink(from: "drug:pyridostigmine", to: "drug:succinylcholine", relation: .seeAlso),
            EntryLink(from: "diagnosis:anti-nmda-encephalitis", to: "drug:rituximab", relation: .seeAlso),
            EntryLink(from: "diagnosis:lambert-eaton", to: "diagnosis:sclc", relation: .seeAlso),
            EntryLink(from: "diagnosis:lambert-eaton", to: "diagnosis:lung-cancer", relation: .seeAlso),
            EntryLink(from: "diagnosis:restless-legs-syndrome", to: "drug:gabapentin", relation: .seeAlso),
            EntryLink(from: "diagnosis:restless-legs-syndrome", to: "drug:pregabalin", relation: .seeAlso),
            EntryLink(from: "diagnosis:acute-mania", to: "drug:lithium", relation: .seeAlso),
            EntryLink(from: "diagnosis:alcohol-use-disorder", to: "drug:naltrexone", relation: .seeAlso),
            EntryLink(from: "diagnosis:alcohol-use-disorder", to: "drug:acamprosate", relation: .seeAlso),
            EntryLink(from: "diagnosis:alcohol-use-disorder", to: "drug:disulfiram", relation: .seeAlso),
            EntryLink(from: "diagnosis:alcohol-withdrawal", to: "reference:ciwa-ar", relation: .seeAlso),
            EntryLink(from: "reference:headache-evaluation", to: "diagnosis:migraine", relation: .seeAlso),
            EntryLink(from: "reference:headache-evaluation", to: "diagnosis:meningitis", relation: .seeAlso),
            EntryLink(from: "reference:weakness-evaluation", to: "diagnosis:stroke", relation: .seeAlso),
            EntryLink(from: "reference:acute-vision-loss-evaluation", to: "diagnosis:acute-angle-closure-glaucoma", relation: .seeAlso),
            EntryLink(from: "reference:acute-vision-loss-evaluation", to: "diagnosis:stroke", relation: .seeAlso),

            // ===== Oncology =====
            EntryLink(from: "drug:abiraterone", to: "diagnosis:prostate-cancer", relation: .usedFor),
            EntryLink(from: "drug:abiraterone", to: "diagnosis:castration-resistant-prostate-cancer", relation: .usedFor),
            EntryLink(from: "drug:abiraterone", to: "drug:prednisone", relation: .seeAlso),
            EntryLink(from: "drug:enzalutamide", to: "diagnosis:prostate-cancer", relation: .usedFor),
            EntryLink(from: "drug:nivolumab", to: "drug:ipilimumab", relation: .seeAlso),
            EntryLink(from: "drug:nivolumab", to: "diagnosis:melanoma", relation: .usedFor),
            EntryLink(from: "drug:nivolumab", to: "lab:troponin", relation: .monitorsWith),
            EntryLink(from: "drug:bortezomib", to: "diagnosis:multiple-myeloma", relation: .usedFor),
            EntryLink(from: "drug:bortezomib", to: "drug:acyclovir", relation: .seeAlso),
            EntryLink(from: "drug:tucatinib", to: "drug:trastuzumab", relation: .seeAlso),
            EntryLink(from: "drug:tucatinib", to: "diagnosis:breast-cancer", relation: .usedFor),
            EntryLink(from: "diagnosis:cytokine-release-syndrome", to: "drug:tocilizumab", relation: .seeAlso),
            EntryLink(from: "diagnosis:cytokine-release-syndrome", to: "drug:anakinra", relation: .seeAlso),
            EntryLink(from: "diagnosis:nsclc", to: "diagnosis:lung-cancer", relation: .seeAlso),
            EntryLink(from: "reference:oncologic-emergencies", to: "diagnosis:neutropenic-fever", relation: .seeAlso),

            // ===== Rheum / misc =====
            EntryLink(from: "reference:dmards-traditional-strategies", to: "drug:methotrexate", relation: .seeAlso),
            EntryLink(from: "reference:dmards-traditional-strategies", to: "drug:sulfasalazine", relation: .seeAlso),
            EntryLink(from: "reference:dmards-traditional-strategies", to: "drug:folic-acid", relation: .seeAlso),
            EntryLink(from: "reference:biologic-safety-monitoring", to: "drug:methotrexate", relation: .seeAlso),
            EntryLink(from: "reference:biologic-safety-monitoring", to: "drug:rituximab", relation: .seeAlso),
            EntryLink(from: "reference:vasculitis-classification", to: "drug:cyclophosphamide", relation: .seeAlso),
            EntryLink(from: "reference:vasculitis-classification", to: "drug:rituximab", relation: .seeAlso),
            EntryLink(from: "diagnosis:anca-vasculitis", to: "lab:creatinine", relation: .assessedBy),
            EntryLink(from: "diagnosis:egpa", to: "drug:mepolizumab", relation: .seeAlso),
            EntryLink(from: "diagnosis:egpa", to: "diagnosis:asthma", relation: .seeAlso),
            EntryLink(from: "reference:osteoporosis-screening-frax", to: "drug:denosumab", relation: .seeAlso),
            EntryLink(from: "reference:osteoporosis-screening-frax", to: "drug:teriparatide", relation: .seeAlso),
            EntryLink(from: "reference:osteoporosis-screening-frax", to: "drug:romosozumab", relation: .seeAlso),
            EntryLink(from: "reference:osteoporosis-screening-frax", to: "lab:vitamin-d-25oh", relation: .seeAlso),
            EntryLink(from: "reference:osteoporosis-screening-frax", to: "diagnosis:hip-fracture", relation: .seeAlso),
            EntryLink(from: "diagnosis:adpkd", to: "drug:tolvaptan", relation: .seeAlso),
            EntryLink(from: "diagnosis:acne-vulgaris", to: "drug:isotretinoin", relation: .seeAlso),
            EntryLink(from: "diagnosis:anaphylaxis", to: "diagnosis:anaphylaxis-acute", relation: .seeAlso),
            EntryLink(from: "diagnosis:anaphylaxis-acute", to: "drug:epinephrine", relation: .seeAlso),
            EntryLink(from: "lab:tdm-narrow-therapeutic-index", to: "drug:digoxin", relation: .seeAlso),
            EntryLink(from: "lab:tdm-narrow-therapeutic-index", to: "drug:phenytoin", relation: .seeAlso),
            EntryLink(from: "lab:tdm-narrow-therapeutic-index", to: "drug:lithium", relation: .seeAlso),
            EntryLink(from: "lab:tdm-narrow-therapeutic-index", to: "drug:vancomycin", relation: .seeAlso),
            EntryLink(from: "lab:neonatal-bilirubin-monitoring", to: "lab:bilirubin", relation: .interpretWith),
            EntryLink(from: "lab:chromogranin-a-5-hiaa", to: "drug:octreotide", relation: .seeAlso),
            EntryLink(from: "lab:anca-panel", to: "drug:hydralazine", relation: .seeAlso),
            EntryLink(from: "lab:anca-panel", to: "drug:propylthiouracil", relation: .seeAlso),

            // ===== GI / hepatology =====
            EntryLink(from: "reference:lft-liver-function-interpretation", to: "drug:acetaminophen", relation: .seeAlso),
            EntryLink(from: "reference:lft-liver-function-interpretation", to: "diagnosis:cirrhosis", relation: .seeAlso),
            EntryLink(from: "reference:lft-liver-function-interpretation", to: "lab:bilirubin", relation: .seeAlso),
            EntryLink(from: "reference:cirrhosis-complications-management", to: "diagnosis:cirrhosis", relation: .seeAlso),
            EntryLink(from: "reference:cirrhosis-complications-management", to: "procedure:paracentesis", relation: .seeAlso),
            EntryLink(from: "reference:cirrhosis-complications-management", to: "drug:albumin-iv", relation: .seeAlso),

            // ===== Airway / procedures =====
            EntryLink(from: "procedure:intubation-assist", to: "lab:capnography-etco2", relation: .seeAlso),
            EntryLink(from: "procedure:intubation-assist", to: "drug:propofol", relation: .seeAlso),
            EntryLink(from: "procedure:rapid-sequence-intubation", to: "lab:capnography-etco2", relation: .seeAlso),
            EntryLink(from: "procedure:rapid-sequence-intubation", to: "drug:fentanyl", relation: .seeAlso),
            EntryLink(from: "procedure:iron-iv-administration", to: "drug:ferric-carboxymaltose", relation: .seeAlso),
            EntryLink(from: "procedure:iron-iv-administration", to: "drug:iron-sucrose", relation: .seeAlso),
            EntryLink(from: "reference:dyspnea-evaluation", to: "diagnosis:pneumothorax", relation: .seeAlso),
            EntryLink(from: "reference:dyspnea-evaluation", to: "diagnosis:asthma", relation: .seeAlso),
            EntryLink(from: "reference:opioid-conversion", to: "drug:morphine", relation: .seeAlso),
            EntryLink(from: "reference:opioid-conversion", to: "drug:methadone", relation: .seeAlso),
            EntryLink(from: "reference:opioid-conversion", to: "drug:fentanyl", relation: .seeAlso),
        ]
    }
}
