import Foundation

extension LibraryTopic {
    static let criticalCareAirwayAdditions: [String] = [
        "reference:oxygen-device-bedside-checks",
        "reference:oxygenation-versus-ventilation",
        "reference:high-flow-nasal-cannula-monitoring",
        "reference:noninvasive-ventilation-bedside-assessment",
        "reference:ventilator-bedside-assessment",
        "reference:ventilator-waveform-observation",
        "reference:patient-ventilator-asynchrony-recognition",
        "reference:auto-peep-and-ineffective-triggering",
        "reference:ventilator-liberation-observation",
        "reference:artificial-airway-secretion-assessment",
        "reference:tracheostomy-bedside-safety-checks",
        "reference:post-extubation-observation",
        "lab:capnography-etco2",
        "procedure:pulse-oximetry",
        "procedure:airway-clearance-therapy",
        "procedure:oral-suctioning",
        "procedure:tracheal-suctioning",
        "reference:difficult-airway-algorithm",
        "diagnosis:refractory-hypoxemia",
        "diagnosis:ventilator-associated-pneumonia",
        "diagnosis:ventilator-induced-lung-injury"
    ]

    static let criticalCareRhythmAdditions: [String] = [
        "reference:telemetry-signal-quality",
        "reference:ecg-rate-and-interval-review",
        "reference:rhythm-change-bedside-assessment",
        "reference:qt-interval-monitoring-context",
        "reference:adult-cpr-quality-review",
        "reference:resuscitation-airway-capnography",
        "reference:post-arrest-assessment-priorities",
        "reference:cardiac-arrest-recovery-support",
        "procedure:twelve-lead-ecg",
        "procedure:synchronized-cardioversion",
        "procedure:code-blue-response",
        "reference:sinus-rhythm-reference",
        "lab:capnography-etco2",
        "lab:potassium",
        "lab:magnesium"
    ]

    static let criticalCareDepthCollections: [LibraryTopic] = [
        .init(id: "oxygen-noninvasive-support", group: .criticalCare, title: "Oxygen & noninvasive support",
              subtitle: "Devices, HFNC, CPAP, bilevel support & reassessment",
              entryIDs: [
                  "reference:oxygen-device-bedside-checks",
                  "reference:oxygenation-versus-ventilation",
                  "reference:high-flow-nasal-cannula-monitoring",
                  "reference:noninvasive-ventilation-bedside-assessment",
                  "procedure:oxygen-administration",
                  "procedure:pulse-oximetry",
                  "reference:home-oxygen-and-oximetry",
                  "reference:cpap-daily-support",
                  "reference:focused-respiratory-assessment",
                  "lab:abg",
                  "reference:abg-algorithm",
                  "diagnosis:refractory-hypoxemia"
              ]),
        .init(id: "invasive-ventilation-liberation", group: .criticalCare, title: "Invasive ventilation & liberation",
              subtitle: "Assessment, synchrony, waveforms & breathing trials",
              entryIDs: [
                  "reference:ventilator-bedside-assessment",
                  "reference:ventilator-waveform-observation",
                  "reference:patient-ventilator-asynchrony-recognition",
                  "reference:auto-peep-and-ineffective-triggering",
                  "reference:ventilator-liberation-observation",
                  "reference:mechanical-ventilation-basics",
                  "reference:mechanical-ventilation-modes-selection",
                  "reference:prone-positioning",
                  "procedure:spontaneous-breathing-trial",
                  "diagnosis:ards",
                  "diagnosis:ventilator-associated-pneumonia",
                  "diagnosis:ventilator-induced-lung-injury",
                  "reference:post-extubation-observation",
                  "reference:artificial-airway-secretion-assessment",
                  "reference:abcdef-bundle",
                  "reference:rass-scale",
                  "lab:capnography-etco2"
              ]),
        .init(id: "artificial-airway-care", group: .criticalCare, title: "Artificial airway care",
              subtitle: "Tracheostomy, suctioning, cuff care & extubation",
              entryIDs: [
                  "reference:artificial-airway-secretion-assessment",
                  "reference:tracheostomy-bedside-safety-checks",
                  "reference:post-extubation-observation",
                  "procedure:intubation-assist",
                  "procedure:ett-cuff-management",
                  "procedure:tracheostomy-care",
                  "procedure:tracheal-suctioning",
                  "procedure:oral-suctioning",
                  "procedure:airway-clearance-therapy",
                  "reference:difficult-airway-algorithm",
                  "scenario:trach-emergency-scenario",
                  "reference:hospital-oral-care",
                  "reference:communication-when-speech-is-limited",
                  "lab:capnography-etco2"
              ]),
        .init(id: "rhythm-monitoring", group: .criticalCare, title: "Rhythm monitoring",
              subtitle: "Telemetry, ECG intervals, QT & clinical correlation",
              entryIDs: [
                  "reference:telemetry-signal-quality",
                  "reference:ecg-rate-and-interval-review",
                  "reference:rhythm-change-bedside-assessment",
                  "reference:qt-interval-monitoring-context",
                  "reference:ecg-12-lead-basics",
                  "reference:dysrhythmia-identification",
                  "reference:av-blocks-reference",
                  "reference:sinus-rhythm-reference",
                  "procedure:twelve-lead-ecg",
                  "procedure:transcutaneous-pacing",
                  "procedure:synchronized-cardioversion",
                  "diagnosis:atrial-fibrillation",
                  "diagnosis:ventricular-tachycardia",
                  "diagnosis:ventricular-fibrillation",
                  "lab:potassium",
                  "lab:magnesium"
              ]),
        .init(id: "resuscitation-post-arrest", group: .criticalCare, title: "Resuscitation & post-arrest",
              subtitle: "Adult CPR, capnography, organ support & recovery",
              entryIDs: [
                  "reference:adult-cpr-quality-review",
                  "reference:resuscitation-airway-capnography",
                  "reference:post-arrest-assessment-priorities",
                  "reference:cardiac-arrest-recovery-support",
                  "procedure:adult-bls",
                  "procedure:code-blue-response",
                  "reference:code-blue-roles",
                  "reference:crash-cart-contents",
                  "scenario:code-blue-team-scenario",
                  "procedure:intubation-assist",
                  "lab:capnography-etco2",
                  "reference:post-icu-recovery"
              ])
    ] + icuEvidenceDraftCollections
}
