import Foundation

public enum LibraryTopicGroup: String, CaseIterable, Hashable, Sendable, Identifiable {
    case criticalCare, bedside, bodySystems, specialties

    public var id: String { rawValue }

    var title: String {
        switch self {
        case .criticalCare: "ICU & critical care"
        case .bedside: "Bedside nursing"
        case .bodySystems: "Body systems"
        case .specialties: "Specialty nursing"
        }
    }

    var subtitle: String {
        switch self {
        case .criticalCare: "Ventilation, shock, drips & monitoring"
        case .bedside: "Assessment, safety & everyday care"
        case .bodySystems: "Conditions, tests & related care"
        case .specialties: "Emergency, maternity, pediatrics & more"
        }
    }

    var topics: [LibraryTopic] { LibraryTopic.all.filter { $0.group == self } }
}

struct LibraryTopic: Identifiable, Sendable {
    let id: String
    let group: LibraryTopicGroup
    let title: String
    let subtitle: String
    let entryIDs: [String]

    func entries(in registry: ContentRegistry) -> [LibraryEntry] {
        entryIDs.compactMap { registry.entry(byID: $0) }
            .sorted { $0.title.localizedCaseInsensitiveCompare($1.title) == .orderedAscending }
    }

    static func topic(id: String) -> LibraryTopic? { all.first { $0.id == id } }

    // Explicit membership keeps incidental body-text mentions out of clinical collections.
    // These are selected reading lists; the A–Z index remains the complete catalog.
    static let all: [LibraryTopic] = [
        .init(id: "shock-perfusion", group: .criticalCare, title: "Shock & perfusion",
              subtitle: "Hemodynamics, sepsis & vasoactive infusions",
              entryIDs: ["reference:shock-hemodynamic-patterns", "reference:shock-classification",
                         "diagnosis:sepsis", "diagnosis:septic-shock", "diagnosis:cardiogenic-shock",
                         "diagnosis:hypovolemic-shock", "diagnosis:obstructive-shock",
                         "lab:lactate", "drip:norepinephrine-drip", "drip:vasopressin-drip",
                         "drip:dobutamine-drip", "reference:arterial-line-management",
                         "reference:sepsis-recovery-support"]),
        .init(id: "airway-ventilation", group: .criticalCare, title: "Airway & ventilation",
              subtitle: "Oxygen support, ventilators & blood gases",
              entryIDs: ["reference:mechanical-ventilation-basics", "reference:mechanical-ventilation-modes-selection",
                         "reference:prone-positioning", "diagnosis:ards", "lab:abg",
                         "reference:abg-algorithm", "procedure:intubation-assist",
                         "procedure:ett-cuff-management", "procedure:spontaneous-breathing-trial",
                         "procedure:tracheostomy-care", "procedure:oxygen-administration",
                         "scenario:trach-emergency-scenario",
                         "reference:focused-respiratory-assessment", "reference:hospital-oral-care",
                         "reference:bronchiectasis-daily-airway-care"]),
        .init(id: "rhythms-resuscitation", group: .criticalCare, title: "Rhythms & resuscitation",
              subtitle: "ECGs, pacing & code-team reference",
              entryIDs: ["reference:ecg-12-lead-basics", "reference:dysrhythmia-identification",
                         "reference:av-blocks-reference", "diagnosis:atrial-fibrillation",
                         "diagnosis:ventricular-tachycardia", "diagnosis:ventricular-fibrillation",
                         "reference:code-blue-roles", "reference:crash-cart-contents",
                         "procedure:adult-bls", "procedure:transcutaneous-pacing",
                         "drip:amiodarone-drip", "scenario:code-blue-team-scenario"]),
        .init(id: "sedation-delirium", group: .criticalCare, title: "Sedation, pain & delirium",
              subtitle: "Assessment scales & ICU liberation",
              entryIDs: ["reference:rass-scale", "reference:cam-icu-delirium", "reference:abcdef-bundle",
                         "reference:pain-scales", "diagnosis:icu-delirium", "drip:propofol-drip",
                         "drip:dexmedetomidine-drip", "drip:fentanyl-drip", "drip:midazolam-drip",
                         "scenario:recognizing-delirium-scenario", "scenario:opioid-oversedation-scenario",
                         "reference:post-icu-recovery", "reference:hospital-sleep-support", "reference:communication-when-speech-is-limited"]),
        .init(id: "neurocritical-care", group: .criticalCare, title: "Neurocritical care",
              subtitle: "Neuro checks, stroke & intracranial monitoring",
              entryIDs: ["procedure:neuro-check", "reference:gcs-detail", "reference:nihss",
                         "reference:icp-cpp-reference", "reference:external-ventricular-drain",
                         "diagnosis:increased-icp", "diagnosis:severe-tbi", "diagnosis:stroke",
                         "procedure:mechanical-thrombectomy-care", "scenario:stroke-alert-scenario",
                         "scenario:seizure-response-scenario"]),
        .init(id: "renal-metabolic-critical-care", group: .criticalCare, title: "Renal & metabolic support",
              subtitle: "CRRT, electrolytes & glucose emergencies",
              entryIDs: ["diagnosis:aki", "reference:kdigo-aki-staging", "procedure:crrt-setup",
                         "lab:potassium", "lab:sodium", "lab:magnesium", "lab:glucose",
                         "reference:electrolyte-repletion-principles", "reference:dka-vs-hhs",
                         "diagnosis:dka", "drip:insulin-drip", "scenario:hyperkalemia-ekg-scenario"]),
        .init(id: "critical-care-devices", group: .criticalCare, title: "Lines, drains & devices",
              subtitle: "Vascular access, chest drains & support devices",
              entryIDs: ["reference:central-venous-catheter", "reference:arterial-line-management",
                         "procedure:central-line-dressing", "procedure:picc-line-management",
                         "procedure:chest-tube-care", "reference:chest-tube-drainage",
                         "reference:external-ventricular-drain", "reference:ecmo-basics",
                         "reference:iabp-care", "reference:percutaneous-vad-impella",
                         "scenario:chest-tube-emergency-scenario",
                         "reference:alarm-fatigue-and-safety"]),
        .init(id: "assessment-deterioration", group: .bedside, title: "Assessment & deterioration",
              subtitle: "Vital signs, focused assessment & escalation",
              entryIDs: ["reference:nursing-care-plan-evaluation",
                         "reference:vital-signs-age", "reference:pain-scales", "procedure:neuro-check",
                         "procedure:orthostatic-vitals", "procedure:pulse-oximetry",
                         "reference:post-op-assessment", "scenario:rapid-response-scenario",
                         "scenario:failure-to-rescue-scenario", "scenario:sepsis-recognition-scenario",
                         "communication:chain-of-command-escalation",
                         "reference:adult-head-to-toe-assessment", "reference:adult-health-history", "reference:focused-respiratory-assessment", "reference:focused-cardiovascular-assessment", "reference:focused-abdominal-assessment", "reference:nursing-documentation-principles"]),
        .init(id: "medication-transfusion-safety", group: .bedside, title: "Medication & transfusion safety",
              subtitle: "Administration, high-alert medicines & blood products",
              entryIDs: ["reference:rights-of-medication", "reference:high-alert-medications",
                         "reference:confused-drug-names", "reference:do-not-crush",
                         "reference:error-prone-abbreviations", "procedure:iv-push-medication",
                         "procedure:enteral-medication-tube", "procedure:subcutaneous-injection",
                         "procedure:im-injection", "procedure:blood-transfusion",
                         "reference:transfusion-reaction-protocol", "scenario:medication-near-miss-scenario",
                         "reference:bleeding-disorder-procedure-planning", "reference:thalassemia-treatment-monitoring-support"]),
        .init(id: "labs-specimens", group: .bedside, title: "Labs & specimen collection",
              subtitle: "Common panels, interpretation & collection",
              entryIDs: ["reference:reading-lab-results", "reference:laboratory-test-preparation",
                         "reference:lab-panels", "reference:lab-tube-colors",
                         "reference:cbc-interpretation-comprehensive", "reference:bmp-cmp-interpretation",
                         "reference:coagulation-panel-interpretation", "reference:urinalysis-interpretation",
                         "reference:abg-algorithm", "procedure:venipuncture",
                         "procedure:blood-culture-collection", "procedure:clean-catch-urine",
                         "procedure:capillary-blood-glucose", "procedure:abg-sampling",
                         "reference:stool-sample-collection"]),
        .init(id: "infection-prevention", group: .bedside, title: "Infection prevention",
              subtitle: "Precautions, PPE & device-associated infection",
              entryIDs: ["reference:standard-precautions", "reference:contact-precautions",
                         "reference:droplet-precautions", "reference:airborne-precautions",
                         "procedure:ppe-don-doff", "procedure:hand-hygiene",
                         "reference:clabsi-bundle", "reference:cauti-bundle",
                         "reference:bloodborne-pathogen-exposure", "reference:antimicrobial-stewardship",
                         "reference:sterile-field-principles", "reference:hospital-oral-care"]),
        .init(id: "skin-mobility-comfort", group: .bedside, title: "Skin, mobility & comfort",
              subtitle: "Wounds, pressure injuries, falls & pain",
              entryIDs: ["reference:stroke-recovery-daily-support",
                         "reference:wound-care-fundamentals", "reference:wound-dressing-selection",
                         "reference:npiap-pressure-injury-staging", "reference:braden-scale",
                         "reference:morse-falls", "procedure:mechanical-lift",
                         "procedure:ambulatory-aid-teaching", "procedure:wound-dressing-change",
                         "procedure:wound-vac", "reference:non-pharmacologic-pain-management",
                         "scenario:pressure-injury-prevention-scenario",
                         "reference:musculoskeletal-assessment", "reference:skin-assessment-beyond-wounds", "reference:bedside-mobility-assessment", "reference:hospital-sleep-support",
                         "reference:rheumatoid-arthritis-daily-function",
                         "reference:eczema-daily-skin-care",
                         "reference:psoriasis-daily-skin-support",
                         "reference:multiple-sclerosis-fatigue-support",
                         "reference:fibromyalgia-sleep-pacing-support",
                         "reference:balance-symptom-history-safety", "reference:hidradenitis-daily-skin-support"]),
        .init(id: "nutrition-elimination", group: .bedside, title: "Nutrition & elimination",
              subtitle: "Feeding tubes, nutrition, urinary & ostomy care",
              entryIDs: ["reference:dialysis-nutrition-and-fluids",
                         "reference:urinary-continence-support",
                         "reference:urostomy-daily-care",
                         "reference:bowel-ostomy-daily-support",
                         "reference:dysphagia-mealtime-support",
                         "reference:therapeutic-diets", "procedure:ng-tube", "procedure:ng-feeding",
                         "procedure:peg-tube-management", "procedure:jejunostomy-tube-care",
                         "procedure:tpn-administration", "procedure:foley-catheter-management",
                         "procedure:foley-removal", "procedure:bladder-scan",
                         "procedure:ostomy-care", "procedure:continuous-bladder-irrigation",
                         "reference:fluid-balance-monitoring", "reference:bedside-nutrition-assessment", "reference:hospital-oral-care",
                         "reference:dementia-mealtime-support",
                         "reference:fecal-incontinence-support",
                         "reference:urinary-retention-recognition",
                         "reference:celiac-disease-food-planning",
                         "reference:gastroparesis-nutrition-support",
                         "reference:ibd-nutrition-follow-up",
                         "reference:gerd-daily-care-follow-up",
                         "reference:interstitial-cystitis-daily-support",
                         "reference:smell-taste-safety-nutrition"]),
        .init(id: "communication-transitions", group: .bedside, title: "Communication & transitions",
              subtitle: "Handoffs, teaching, discharge & goals of care",
              entryIDs: ["reference:conservative-kidney-care",
                         "communication:sbar", "communication:ipass", "communication:check-back",
                         "communication:cus-assertive", "communication:interpreter-use",
                         "reference:health-literacy-teach-back", "reference:discharge-teaching-framework",
                         "reference:delegation-scope-of-practice", "reference:advance-directives-polst",
                         "reference:eol-comfort-care", "communication:family-communication-crisis",
                         "scenario:prioritization-scenario",
                         "reference:hearing-loss-communication", "reference:low-vision-bedside-support", "reference:aphasia-communication-support", "reference:cultural-preferences-assessment", "reference:spiritual-support-in-hospital", "reference:communication-when-speech-is-limited",
                         "reference:dementia-communication-support",
                         "reference:dementia-home-and-respite-support",
                         "reference:kidney-transplant-follow-up",
                         "reference:sepsis-recovery-support",
                         "reference:hiv-treatment-continuity-support",
                         "reference:sickle-cell-everyday-care-planning", "reference:thalassemia-treatment-monitoring-support"]),
        .init(id: "cardiovascular", group: .bodySystems, title: "Cardiovascular",
              subtitle: "Cardiac conditions, rhythms & vascular care",
              entryIDs: ["diagnosis:heart-failure", "diagnosis:atrial-fibrillation", "diagnosis:cardiogenic-shock",
                         "reference:ecg-12-lead-basics", "reference:heart-failure-teaching",
                         "reference:chest-pain-evaluation", "lab:troponin", "procedure:ekg-12-lead-procedure",
                         "drip:diltiazem-drip", "drip:nitroglycerin-drip",
                         "reference:focused-cardiovascular-assessment", "reference:fluid-balance-monitoring",
                         "reference:cardiac-rehabilitation-recovery",
                         "reference:home-blood-pressure-measurement",
                         "reference:pulmonary-hypertension-follow-up-support"]),
        .init(id: "respiratory", group: .bodySystems, title: "Respiratory",
              subtitle: "Airways, oxygenation & lung conditions",
              entryIDs: ["reference:cpap-daily-support",
                         "reference:home-oxygen-and-oximetry",
                         "reference:pulmonary-rehabilitation-support",
                         "diagnosis:pneumonia", "diagnosis:ards", "reference:dyspnea-evaluation",
                         "reference:copd-discharge-teaching", "lab:abg", "procedure:oxygen-administration",
                         "procedure:incentive-spirometry", "procedure:mdi-inhaler-teaching",
                         "procedure:chest-tube-care", "procedure:tracheostomy-care",
                         "reference:asthma-action-plan-daily-support",
                         "reference:latent-tb-treatment-support",
                         "reference:bronchiectasis-daily-airway-care", "reference:ipf-daily-care-follow-up", "reference:pulmonary-hypertension-follow-up-support"]),
        .init(id: "neurological", group: .bodySystems, title: "Neurological",
              subtitle: "Stroke, seizures, cognition & assessment",
              entryIDs: ["reference:stroke-recovery-daily-support",
                         "reference:dysphagia-mealtime-support",
                         "diagnosis:stroke", "diagnosis:delirium", "diagnosis:increased-icp",
                         "reference:gcs-detail", "reference:nihss", "procedure:neuro-check",
                         "reference:altered-mental-status-evaluation", "procedure:lumbar-puncture-assist",
                         "lab:csf-analysis", "scenario:seizure-response-scenario",
                         "reference:epilepsy-daily-self-management",
                         "reference:multiple-sclerosis-fatigue-support",
                         "reference:balance-symptom-history-safety"]),
        .init(id: "renal-urinary", group: .bodySystems, title: "Renal & urinary",
              subtitle: "Kidney function, electrolytes & urinary care",
              entryIDs: ["reference:hemodialysis-nursing-support",
                         "reference:peritoneal-dialysis-daily-care",
                         "reference:dialysis-nutrition-and-fluids",
                         "reference:conservative-kidney-care",
                         "reference:urinary-continence-support",
                         "reference:urostomy-daily-care",
                         "diagnosis:aki", "diagnosis:uti", "reference:ckd-staging",
                         "reference:urinalysis-interpretation", "lab:potassium", "lab:sodium",
                         "procedure:crrt-setup", "procedure:foley-catheter-management",
                         "procedure:bladder-scan", "scenario:dialysis-day-scenario",
                         "reference:kidney-medication-safety",
                         "reference:kidney-transplant-follow-up",
                         "reference:urinary-retention-recognition",
                         "reference:interstitial-cystitis-daily-support"]),
        .init(id: "gastrointestinal", group: .bodySystems, title: "Gastrointestinal & liver",
              subtitle: "Digestive conditions, liver function & nutrition",
              entryIDs: ["reference:bowel-ostomy-daily-support",
                         "diagnosis:cirrhosis", "diagnosis:acute-pancreatitis", "diagnosis:upper-gi-bleed",
                         "reference:abdominal-pain-evaluation", "reference:lft-liver-function-interpretation",
                         "procedure:ng-tube", "procedure:ostomy-care", "procedure:paracentesis-assist",
                         "procedure:tpn-administration", "drip:octreotide-drip",
                         "reference:focused-abdominal-assessment",
                         "reference:celiac-disease-food-planning",
                         "reference:gastroparesis-nutrition-support",
                         "reference:ibd-nutrition-follow-up",
                         "reference:gerd-daily-care-follow-up",
                         "reference:hepatitis-b-daily-care-prevention",
                         "reference:hepatitis-c-treatment-follow-up"]),
        .init(id: "endocrine-metabolic", group: .bodySystems, title: "Endocrine & metabolic",
              subtitle: "Diabetes, glucose & hormone disorders",
              entryIDs: ["diagnosis:dka", "diagnosis:diabetes-insipidus", "reference:dka-vs-hhs",
                         "reference:insulin-types", "reference:diabetes-self-management-teaching",
                         "lab:glucose", "procedure:capillary-blood-glucose", "drip:insulin-drip",
                         "scenario:hypoglycemia-npo-scenario",
                         "reference:continuous-glucose-monitor-teaching"]),
        .init(id: "blood-infection", group: .bodySystems, title: "Blood & immune system",
              subtitle: "Hematology, coagulation & infection",
              entryIDs: ["diagnosis:iron-deficiency-anemia", "diagnosis:hit", "diagnosis:sepsis",
                         "reference:cbc-interpretation-comprehensive", "reference:coagulation-panel-interpretation",
                         "reference:anticoagulation-teaching", "procedure:blood-transfusion",
                         "procedure:blood-culture-collection", "drip:heparin-drip",
                         "reference:neutropenic-precautions",
                         "reference:lupus-daily-care-follow-up",
                         "reference:hepatitis-b-daily-care-prevention",
                         "reference:hepatitis-c-treatment-follow-up",
                         "reference:latent-tb-treatment-support",
                         "reference:hiv-treatment-continuity-support",
                         "reference:sickle-cell-everyday-care-planning", "reference:bleeding-disorder-procedure-planning", "reference:thalassemia-treatment-monitoring-support"]),
        .init(id: "musculoskeletal-skin", group: .bodySystems, title: "Musculoskeletal & skin",
              subtitle: "Mobility, neurovascular checks & skin integrity",
              entryIDs: ["diagnosis:pressure-injury", "reference:wound-care-fundamentals",
                         "reference:fall-fracture-prevention", "procedure:cast-care",
                         "procedure:traction-setup", "procedure:ambulatory-aid-teaching",
                         "procedure:wound-dressing-change", "procedure:burn-wound-care",
                         "scenario:compartment-syndrome-scenario",
                         "reference:musculoskeletal-assessment", "reference:skin-assessment-beyond-wounds",
                         "reference:rheumatoid-arthritis-daily-function",
                         "reference:hip-replacement-home-preparation",
                         "reference:eczema-daily-skin-care",
                         "reference:psoriasis-daily-skin-support",
                         "reference:lupus-daily-care-follow-up",
                         "reference:fibromyalgia-sleep-pacing-support",
                         "reference:hidradenitis-daily-skin-support"]),
        .init(id: "emergency-nursing", group: .specialties, title: "Emergency & trauma",
              subtitle: "Triage, emergency assessment & team response",
              entryIDs: ["reference:esi-triage", "reference:atls-primary-survey",
                         "reference:trauma-team-activation-criteria", "reference:code-blue-roles",
                         "reference:toxidromes-recognition", "procedure:intraosseous-access",
                         "procedure:intubation-assist", "reference:massive-transfusion-protocol",
                         "communication:call-out", "scenario:anaphylaxis-scenario"]),
        .init(id: "perioperative-nursing", group: .specialties, title: "Perioperative care",
              subtitle: "Surgical safety, recovery & post-op assessment",
              entryIDs: ["reference:who-surgical-safety-checklist", "procedure:surgical-time-out",
                         "reference:informed-consent-framework", "reference:post-op-assessment",
                         "procedure:pca-setup", "procedure:epidural-catheter-management",
                         "procedure:incentive-spirometry", "scenario:covert-hemorrhage-scenario",
                         "scenario:wrong-site-surgery-scenario",
                         "reference:hip-replacement-home-preparation",
                         "reference:cataract-surgery-recovery-teaching",
                         "reference:bleeding-disorder-procedure-planning"]),
        .init(id: "maternity-newborn", group: .specialties, title: "Maternity & newborn",
              subtitle: "Maternal assessment, labor, postpartum & newborn care",
              entryIDs: ["reference:maternal-vital-signs", "reference:fetal-heart-rate",
                         "reference:stages-of-labor", "reference:postpartum-assessment-bubblele",
                         "procedure:fundal-massage", "procedure:newborn-assessment",
                         "reference:apgar-score", "reference:neonatal-jaundice",
                         "reference:breastfeeding-counseling", "scenario:pph-scenario"]),
        .init(id: "pediatric-nursing", group: .specialties, title: "Pediatrics",
              subtitle: "Age-specific assessment, development & common conditions",
              entryIDs: ["reference:pediatric-vitals", "reference:pediatric-developmental-milestones",
                         "reference:pediatric-pain-scales", "procedure:flacc",
                         "procedure:pediatric-iv-start", "diagnosis:croup",
                         "reference:bronchiolitis-rsv", "reference:car-seat-safety",
                         "scenario:peds-respiratory-distress-scenario", "scenario:peds-dka-scenario"]),
        .init(id: "oncology-nursing", group: .specialties, title: "Oncology",
              subtitle: "Treatment safety, access devices & supportive care",
              entryIDs: ["reference:chemo-administration-safety", "reference:chemo-extravasation",
                         "reference:neutropenic-precautions", "reference:oncologic-emergencies",
                         "procedure:implanted-port-care", "procedure:radiation-therapy-nursing-care",
                         "procedure:ici-monitoring", "reference:cinv-management",
                         "scenario:neutropenic-fever-scenario",
                         "reference:cancer-related-fatigue", "reference:cancer-treatment-neuropathy", "reference:cancer-treatment-cognitive-changes", "reference:cancer-mouth-throat-care", "reference:cancer-treatment-diarrhea-support", "reference:cancer-treatment-constipation-support", "reference:cancer-related-lymphedema", "reference:cancer-fertility-counseling", "reference:cancer-sexual-health-support", "reference:cancer-body-image-support", "reference:cancer-survivorship-care-plan", "reference:cancer-financial-barriers", "reference:food-safety-weakened-immunity"]),
        .init(id: "eye-hearing-care", group: .specialties, title: "Eye & hearing care",
              subtitle: "Vision support, hearing devices & recovery",
              entryIDs: ["reference:cataract-surgery-recovery-teaching", "reference:hearing-aid-daily-support",
                         "reference:low-vision-bedside-support", "reference:hearing-loss-communication",
                         "procedure:eye-drops", "diagnosis:ssnhl",
                         "reference:sjogren-eye-mouth-support",
                         "reference:tinnitus-assessment-coping-support", "reference:balance-symptom-history-safety"]),
        .init(id: "older-adult-care", group: .specialties, title: "Older adult care",
              subtitle: "Function, cognition, falls & comfort",
              entryIDs: ["procedure:comprehensive-geriatric-assessment", "reference:geriatric-frailty-assessment",
                         "reference:fall-fracture-prevention", "reference:beers-criteria",
                         "procedure:painad", "diagnosis:delirium", "reference:advance-directives-polst",
                         "reference:eol-comfort-care", "scenario:recognizing-delirium-scenario",
                         "reference:heat-health-planning", "reference:home-medical-device-preparedness",
                         "reference:dementia-personal-care",
                         "reference:dementia-mealtime-support",
                         "reference:dementia-communication-support",
                         "reference:dementia-wandering-safety",
                         "reference:dementia-sleep-and-sundowning",
                         "reference:dementia-hospital-care",
                         "reference:dementia-meaningful-activities",
                         "reference:dementia-home-and-respite-support",
                         "reference:tinnitus-assessment-coping-support", "reference:balance-symptom-history-safety", "reference:smell-taste-safety-nutrition"]),
        .init(id: "behavioral-health", group: .specialties, title: "Behavioral health",
              subtitle: "Therapeutic communication, safety & substance use",
              entryIDs: ["reference:mental-status-exam", "reference:c-ssrs-overview",
                         "procedure:suicide-precautions", "reference:trauma-informed-care",
                         "communication:therapeutic-communication", "communication:verbal-deescalation",
                         "reference:ciwa-ar", "reference:cows-reference", "reference:sbirt",
                         "scenario:suicide-risk-scenario",
                         "reference:psychotherapy-preparation-follow-up"]),
        .init(id: "community-home-care", group: .specialties, title: "Community & home care",
              subtitle: "Prevention, home support & environmental safety",
              entryIDs: ["reference:food-safety-weakened-immunity",
                         "reference:tick-removal-and-follow-up",
                         "reference:mosquito-bite-prevention",
                         "reference:heat-health-planning",
                         "reference:wildfire-smoke-protection",
                         "reference:home-carbon-monoxide-prevention",
                         "reference:drinking-water-advisories",
                         "reference:home-cleaning-and-disinfection",
                         "reference:home-medical-device-preparedness",
                         "reference:home-safety-fall-prevention-bundle",
                         "reference:discharge-teaching-framework",
                         "reference:health-literacy-teach-back",
                         "reference:dementia-home-and-respite-support",
                         "reference:dementia-wandering-safety",
                         "reference:kidney-medication-safety",
                         "reference:home-blood-pressure-measurement",
                         "reference:continuous-glucose-monitor-teaching",
                         "reference:asthma-action-plan-daily-support",
                         "reference:sepsis-recovery-support",
                         "reference:hepatitis-b-daily-care-prevention",
                         "reference:hepatitis-c-treatment-follow-up",
                         "reference:latent-tb-treatment-support",
                         "reference:hiv-treatment-continuity-support",
                         "reference:bronchiectasis-daily-airway-care", "reference:ipf-daily-care-follow-up", "reference:pulmonary-hypertension-follow-up-support", "reference:sickle-cell-everyday-care-planning", "reference:smell-taste-safety-nutrition", "reference:hidradenitis-daily-skin-support"]),
        .init(id: "nursing-workplace-health", group: .bedside, title: "Nursing workplace health",
              subtitle: "Fatigue, occupational protection & support",
              entryIDs: ["reference:nursing-shift-work-fatigue",
                         "reference:respirator-fit-and-seal-check",
                         "reference:nursing-workplace-violence",
                         "reference:workplace-cleaning-chemical-safety",
                         "reference:nursing-mental-health-support",
                         "procedure:ppe-don-doff",
                         "procedure:mechanical-lift",
                         "communication:verbal-deescalation"])
    ] + medlinePlusCollections
}
