import Foundation

extension LibraryTopic {
    static let medlinePlusCollections: [LibraryTopic] = [
        .init(id: "nlm-oncology-genetics", group: .specialties, title: "Cancer testing & genetics",
              subtitle: "Biomarkers, inherited risk and tissue testing", entryIDs: [
                  "reference:test-guide-bcr-abl1-genetic-test",
                  "reference:test-guide-beta-2-microglobulin-b2m-tumor-marker-test",
                  "reference:test-guide-braf-genetic-test",
                  "reference:test-guide-brca-test",
                  "reference:test-guide-breast-biopsy",
                  "reference:test-guide-estrogen-receptor-progesterone-receptor-tests",
                  "reference:test-guide-free-light-chains",
                  "reference:test-guide-her2-tumor-marker-test",
                  "reference:test-guide-lung-cancer-genetic-tests",
                  "reference:test-guide-pdl1-immunotherapy-tests",
                  "reference:test-guide-pten-genetic-test",
                  "reference:test-guide-sentinel-lymph-node-biopsy",
                  "reference:test-guide-thyroglobulin",
                  "reference:test-guide-tp53-genetic-test",
                  "reference:test-guide-pharmacogenetic-tests",
              ]),
        .init(id: "nlm-neurology-sensory", group: .specialties, title: "Neurologic, hearing & balance tests",
              subtitle: "Nerves, cognition, sleep and sensory testing", entryIDs: [
                  "reference:test-guide-autonomic-testing",
                  "reference:test-guide-balance-tests",
                  "reference:test-guide-cognitive-testing",
                  "reference:test-guide-concussion-tests",
                  "reference:test-guide-electromyography-emg-and-nerve-conduction-studies",
                  "reference:test-guide-hearing-tests-for-adults",
                  "reference:test-guide-myasthenia-gravis-tests",
                  "reference:test-guide-myelography",
                  "reference:test-guide-videonystagmography-vng",
                  "reference:test-guide-sleep-study",
                  "reference:test-guide-glaucoma-tests",
                  "reference:test-guide-csf-immunoglobulin-g-igg-index",
                  "reference:test-guide-fall-risk-assessment",
                  "reference:test-guide-vision-screening",
              ]),
        .init(id: "nlm-mental-behavioral", group: .specialties, title: "Behavioral health screening",
              subtitle: "Assessment, screening limits and test anxiety", entryIDs: [
                  "reference:test-guide-adhd-screening",
                  "reference:test-guide-alcohol-use-screening-tests",
                  "reference:test-guide-depression-screening",
                  "reference:test-guide-mental-health-screening",
                  "reference:test-guide-obsessive-compulsive-disorder-ocd-test",
                  "reference:test-guide-panic-disorder-test",
                  "reference:test-guide-suicide-risk-screening",
                  "reference:test-guide-how-to-cope-with-medical-test-anxiety",
              ]),
        .init(id: "nlm-gastrointestinal", group: .specialties, title: "Digestive diagnostic tests",
              subtitle: "Stool studies, motility, imaging and endoscopy", entryIDs: [
                  "reference:test-guide-anoscopy",
                  "reference:test-guide-appendicitis-tests",
                  "reference:test-guide-barium-swallow",
                  "reference:test-guide-calprotectin-stool-test",
                  "reference:test-guide-chymotrypsin-in-stool",
                  "reference:test-guide-colorectal-cancer-screening-tests",
                  "reference:test-guide-elastography",
                  "reference:test-guide-esophageal-ph-test",
                  "reference:test-guide-fecal-occult-blood-test-fobt",
                  "reference:test-guide-gastric-emptying-tests",
                  "reference:test-guide-lactose-tolerance-tests",
                  "reference:test-guide-ova-and-parasite-test",
                  "reference:test-guide-stool-elastase",
                  "reference:test-guide-white-blood-cell-wbc-in-stool",
                  "reference:test-guide-xylose-testing",
                  "reference:test-guide-helicobacter-pylori-h-pylori-tests",
              ]),
        .init(id: "nlm-reproductive", group: .specialties, title: "Reproductive & prenatal testing",
              subtitle: "Fertility, pregnancy and reproductive health", entryIDs: [
                  "reference:test-guide-amniocentesis-amniotic-fluid-test",
                  "reference:test-guide-bacterial-vaginosis-test",
                  "reference:test-guide-chlamydia-test",
                  "reference:test-guide-chorionic-villus-sampling-cvs",
                  "reference:test-guide-colposcopy",
                  "reference:test-guide-estrogen-levels-test",
                  "reference:test-guide-follicle-stimulating-hormone-fsh-levels-test",
                  "reference:test-guide-gonorrhea-test",
                  "reference:test-guide-human-papillomavirus-hpv-test",
                  "reference:test-guide-hysteroscopy",
                  "reference:test-guide-luteinizing-hormone-lh-levels-test",
                  "reference:test-guide-pap-smear",
                  "reference:test-guide-prenatal-cell-free-dna-screening",
                  "reference:test-guide-prenatal-panel",
                  "reference:test-guide-progesterone-test",
                  "reference:test-guide-semen-analysis",
                  "reference:test-guide-sexually-transmitted-infection-sti-tests",
                  "reference:test-guide-shbg-blood-test",
                  "reference:test-guide-trichomoniasis-test",
              ]),
        .init(id: "nlm-infectious-disease", group: .specialties, title: "Infection testing",
              subtitle: "Cultures, molecular tests and specimen education", entryIDs: [
                  "reference:test-guide-antibiotic-sensitivity-test",
                  "reference:test-guide-antibody-serology-tests",
                  "reference:test-guide-bacteria-culture-test",
                  "reference:test-guide-chickenpox-and-shingles-tests",
                  "reference:test-guide-dengue-fever-test",
                  "reference:test-guide-flu-influenza-test",
                  "reference:test-guide-fungal-culture-test",
                  "reference:test-guide-gram-stain",
                  "reference:test-guide-hepatitis-testing",
                  "reference:test-guide-herpes-hsv-test",
                  "reference:test-guide-legionella-tests",
                  "reference:test-guide-lyme-disease-tests",
                  "reference:test-guide-measles-and-mumps-tests",
                  "reference:test-guide-meningococcal-disease-tests",
                  "reference:test-guide-mononucleosis-mono-tests",
                  "reference:test-guide-mrsa-tests",
                  "reference:test-guide-nasal-swab",
                  "reference:test-guide-parainfluenza-tests",
                  "reference:test-guide-pcr-tests",
                  "reference:test-guide-pneumococcal-disease-tests",
                  "reference:test-guide-rapid-tests",
                  "reference:test-guide-respiratory-pathogens-panel",
                  "reference:test-guide-respiratory-syncytial-virus-rsv-tests",
                  "reference:test-guide-whooping-cough-diagnosis",
                  "reference:test-guide-yeast-infection-tests",
                  "reference:test-guide-zika-virus-test",
                  "reference:test-guide-cytomegalovirus-cmv-tests",
              ]),
        .init(id: "nlm-endocrine-metabolic", group: .specialties, title: "Hormone & metabolic testing",
              subtitle: "Endocrine, metabolic and immune evaluation", entryIDs: [
                  "reference:test-guide-adrenocorticotropic-hormone-acth",
                  "reference:test-guide-alkaline-phosphatase",
                  "reference:test-guide-amylase-test",
                  "reference:test-guide-calcitonin-test",
                  "reference:test-guide-cold-stimulation-test",
                  "reference:test-guide-dhea-sulfate-test",
                  "reference:test-guide-diabetes-tests",
                  "reference:test-guide-diabetic-foot-exam",
                  "reference:test-guide-gamma-glutamyl-transferase-ggt-test",
                  "reference:test-guide-globulin-test",
                  "reference:test-guide-glucagon-blood-test",
                  "reference:test-guide-growth-hormone-tests",
                  "reference:test-guide-immunoglobulins-blood-test",
                  "reference:test-guide-insulin-in-blood",
                  "reference:test-guide-prolactin-levels",
                  "reference:test-guide-17-hydroxyprogesterone",
              ]),
        .init(id: "nlm-renal-urinary", group: .specialties, title: "Urine & urinary tract testing",
              subtitle: "Urine findings, stone analysis and urinary imaging", entryIDs: [
                  "reference:test-guide-bilirubin-in-urine",
                  "reference:test-guide-blood-in-urine",
                  "reference:test-guide-calcium-in-urine-test",
                  "reference:test-guide-crystals-in-urine",
                  "reference:test-guide-epithelial-cells-in-urine",
                  "reference:test-guide-glucose-in-urine-test",
                  "reference:test-guide-intravenous-pyelogram-ivp",
                  "reference:test-guide-ketones-in-urine",
                  "reference:test-guide-kidney-stone-analysis",
                  "reference:test-guide-mucus-in-urine",
                  "reference:test-guide-nitrites-in-urine",
                  "reference:test-guide-phosphate-in-urine",
                  "reference:test-guide-urobilinogen-in-urine",
              ]),
        .init(id: "nlm-hematology", group: .specialties, title: "Blood cell & clotting tests",
              subtitle: "Cell indices, antibodies and coagulation factors", entryIDs: [
                  "reference:test-guide-blood-differential",
                  "reference:test-guide-coagulation-factor-tests",
                  "reference:test-guide-g6pd-test",
                  "reference:test-guide-hemoglobin-electrophoresis",
                  "reference:test-guide-lactate-dehydrogenase-ldh-isoenzymes-test",
                  "reference:test-guide-mcv-mean-corpuscular-volume",
                  "reference:test-guide-mpv-blood-test",
                  "reference:test-guide-porphyrin-tests",
                  "reference:test-guide-protein-c-and-protein-s-tests",
                  "reference:test-guide-rdw-red-cell-distribution-width",
                  "reference:test-guide-red-blood-cell-rbc-count",
                  "reference:test-guide-red-blood-cell-rbc-indices",
                  "reference:test-guide-red-blood-cell-antibody-screen",
                  "reference:test-guide-bone-marrow-tests",
              ]),
        .init(id: "nlm-cardiopulmonary-imaging", group: .specialties, title: "Cardiac, pulmonary & imaging tests",
              subtitle: "Ultrasound, nuclear imaging and function testing", entryIDs: [
                  "reference:test-guide-doppler-ultrasound",
                  "reference:test-guide-echocardiography",
                  "reference:test-guide-fluoroscopy",
                  "reference:test-guide-heart-disease-risk-assessment",
                  "reference:test-guide-lipoprotein-a-blood-test",
                  "reference:test-guide-pet-scan",
                  "reference:test-guide-pleural-fluid-analysis",
                  "reference:test-guide-stress-tests",
                  "reference:test-guide-sonogram",
                  "reference:test-guide-vq-scan",
                  "reference:test-guide-laparoscopy",
              ]),
        .init(id: "nlm-allergy-rheumatology", group: .specialties, title: "Allergy & autoimmune testing",
              subtitle: "Skin tests, antibodies and joint fluid studies", entryIDs: [
                  "reference:test-guide-allergy-skin-test",
                  "reference:test-guide-autoantibody-testing",
                  "reference:test-guide-food-allergy-testing",
                  "reference:test-guide-smooth-muscle-antibody-sma-test",
                  "reference:test-guide-synovial-fluid-analysis",
              ]),
        .init(id: "nlm-diagnostic-preparation", group: .specialties, title: "Diagnostic panels & examinations",
              subtitle: "Common panels, examination and screening concepts", entryIDs: [
                  "reference:test-guide-at-home-medical-tests",
                  "reference:test-guide-basic-metabolic-panel-bmp",
                  "reference:test-guide-complete-blood-count-cbc",
                  "reference:test-guide-comprehensive-metabolic-panel-cmp",
                  "reference:test-guide-dental-exam",
                  "reference:test-guide-differential-diagnosis",
                  "reference:test-guide-electrolyte-panel",
                  "reference:test-guide-heavy-metal-testing",
                  "reference:test-guide-skin-cancer-screening",
                  "reference:test-guide-vitamin-e-tocopherol-test",
                  "reference:test-guide-obesity-screening",
                  "reference:test-guide-opioid-testing",
                  "reference:test-guide-tricyclic-antidepressant-tca-screen",
              ]),
        .init(id: "nlm-pediatric-family-screening", group: .specialties, title: "Child & family screening",
              subtitle: "Development, newborn tests and family preparation", entryIDs: [
                  "reference:test-guide-autism-spectrum-disorder-asd-screening",
                  "reference:test-guide-developmental-and-behavioral-screening-tests",
                  "reference:test-guide-down-syndrome-tests",
                  "reference:test-guide-fetal-alcohol-spectrum-disorders-fasd-screening",
                  "reference:test-guide-hearing-tests-for-children",
                  "reference:test-guide-how-to-prepare-your-child-for-a-lab-test",
                  "reference:test-guide-galactosemia-tests",
                  "reference:test-guide-phenylketonuria-pku-screening",
                  "reference:test-guide-cord-blood-testing-and-banking",
                  "reference:test-guide-postpartum-depression-screening",
              ]),
        .init(id: "nlm-genetic-conditions", group: .specialties, title: "Inherited conditions",
              subtitle: "Features, causes and inheritance patterns", entryIDs: [
                  "reference:genetics-alport-syndrome",
                  "reference:genetics-fabry-disease",
                  "reference:genetics-gaucher-disease",
                  "reference:genetics-pompe-disease",
                  "reference:genetics-spinal-muscular-atrophy",
                  "reference:genetics-myotonic-dystrophy",
                  "reference:genetics-charcot-marie-tooth-disease",
                  "reference:genetics-friedreich-ataxia",
                  "reference:genetics-tuberous-sclerosis-complex",
                  "reference:genetics-neurofibromatosis-type-1",
                  "reference:genetics-osteogenesis-imperfecta",
                  "reference:genetics-ehlers-danlos-syndrome",
                  "reference:genetics-noonan-syndrome",
                  "reference:genetics-williams-syndrome",
                  "reference:genetics-prader-willi-syndrome",
                  "reference:genetics-angelman-syndrome",
                  "reference:genetics-fragile-x-syndrome",
                  "reference:genetics-rett-syndrome",
                  "reference:genetics-22q112-deletion-syndrome",
                  "reference:genetics-achondroplasia",
                  "reference:genetics-klinefelter-syndrome",
                  "reference:genetics-phenylketonuria",
                  "reference:genetics-galactosemia",
                  "reference:genetics-medium-chain-acyl-coa-dehydrogenase-deficiency",
                  "reference:genetics-maple-syrup-urine-disease",
                  "reference:genetics-ornithine-transcarbamylase-deficiency",
                  "reference:genetics-hereditary-hemorrhagic-telangiectasia",
                  "reference:genetics-von-hippel-lindau-syndrome",
                  "reference:genetics-lynch-syndrome",
                  "reference:genetics-familial-adenomatous-polyposis",
                  "reference:genetics-li-fraumeni-syndrome",
                  "reference:genetics-primary-ciliary-dyskinesia",
                  "reference:genetics-neurofibromatosis-type-2",
                  "reference:genetics-usher-syndrome",
              ]),
    ]
}
